log/LICENSE.txt
log/log15adapter/LICENSE.txt
log/pgxadapter/LICENSE.txt

Currently, if you go to https://pkg.go.dev/github.com/ngrok/libngrok-go/log, you get "Documentation not displayed due to license restrictions."
I'm hopeful that this will fix it.
I've tested this by using `go run golang.org/x/pkgsite/cmd/pkgsite` to run it locally and verified that the 'log' submodule has the little 'Redistributable License' tickmark on it with this change.

log: add licenses to submodules

---

tls.go

This:
* Lifts the cert and key fields out of a sub-struct and into the main `TLSConfig`
* Renames `WithEdgeTermination` to `WithTermination`, since it's *always* at the edge.

tls: configuration cleanup

---

example/http.go
libngrok_test.go
scripts/Makefile
session.go

Resolves a few product asks:
* Trims the `Session` interface down to just `Close` and `StartTunnel`
* Stops leaking `proto` types into the public API
* Hides the `ReconnectCookie`, making it an internal implementation detail
Most of the removed functionality is actually just hidden - it can still be accessed via interface assertions since the non-exported implementer of the `Session` interface still has the methods. I figure this should be sufficient if we ever find that we actually do need them internally for something.

session: clean up the public API

---

example/dynamic.go

This is what I showed off internally on Monday.
It uses a pretty naiive HTTP api to start/stop tunnels that do nothing but do oauth and echo the request back.
Builds a little bit on #8, so we should get that merged first.

examples: add dynamic

---

common.go
example/http.go
http.go
labeled.go
session.go
tcp.go
tls.go
tunnel_config.go

Right now it's in the format `app://<hostname>/<executable path>?pid=<process id>`.
We can bikeshed here.
Builds on #12, which should be merged first.

tunnels: auto-define ForwardsTo

---

examples/go.mod
go.work
go.work.sum
log/LICENSE.txt
log/go.mod
log/log15adapter/go.mod
log/pgxadapter/go.mod
logging.go
session.go

The log package was defined as a separate Go module for reasons that seem unncessary. Technically it would let you implement a Logger without needing to import all of the root module's dependencies, but:
1. If you're working with this library, the end application will almost certainly import the root module anyways.
2. The implementing package can still implement the interface without importing any of our package anyways.
The benefit to this change is:
1. The dependency story is simpler to reason about
2. There is no confusing duplication of a Logger interface in both the main package and the subpackage.
Explicitly pulling @euank as a reviewer since this more or less reverts his earlier PR.

remove duplicated logging interface, remove log package go module

---

internal/tunnel/proto/msg.go
session.go

Also sets the library version back to 0.0.0. This means we'll have to wait on ngrok-private/ngrok#13827 to merge/deploy, or else it'll get rejected for having too low a version again.

proto: add ClientType and declare this library as a library

---

config/domain_test.go
config/http.go
config/tls.go
internal/tunnel/proto/msg.go
online_test.go

Follow-up from #46.
Removes the deprecated `Hostname` and `Subdomain` fields for the new and improved `Domain` field.
No externally-visible API changes.

proto: deprecate/remove hostname and subdomain

---

internal/pb/middleware.pb.go
internal/tunnel/proto/msg.go
internal/tunnel/proto/msg_test.go
session.go

Pulling in a security fix from our agent copy.

sec: make sure we don't log the authtoken in plaintext by accident

---

config/forwards_to.go
config/labeled_test.go

Currently, we are not able to set `ForwardsTo` for labeled tunnels. This PR adds the necessary `LabeledTunnelOption` to the returned interface so that we can set `ForwardsTo` for labeled tunnels.

Allow setting ForwardsTo for labeled tunnels

---

session.go

Expose a few more features of the underlying session protocol. Offering `Restart` alongside `Stop` seems reasonable; `Update` is a bit more odd but still a neat feature to offer for more complex applications.
Internally, the `Update` message has a couple fields that could be exposed; however, ngrok internally doesn't use them and they're even less useful in the context of third-party applications, so I don't think there's a need to make those fields available.
Allowing application authors to set reasons for disabling server command handlers is useful in cases where those handlers are only supported on particular platforms or under specific circumstances. Does the documentation for those options make it sufficiently clear that not setting either a handler or a command disabled option still …

Add handlers for Restart and Update server commands, plus fancy unimplemented handler errors

---

session.go
session_test.go

Allows library consumers to differentiate their application and version from others.
Currently, there is no incentive for folks to use this outside of caring about our internal usage; we should expose this to users via the dashboard & API in the future.

session: add user-agent string and allow library consumers to extend it

---

internal/tunnel/proto/msg.go
online_test.go
tunnel.go

Expose the tunnel proto, edge type, and passthrough tls for each connection to a tunnel. Re-export the internal edge type constants so consumers can use constants instead of magic number strings.

add connection proxy metadata

---

errors.go
go.mod
go.sum
online_test.go
session.go

In the case of a temporary failure in ReconnectingSession, an error is placed into the stateChanges channel. This error does not necessarily mean that failure is permanent and that the connection process should abort. For example, in the case of a dial error when initially connecting the session, we desire to retry dialing with backoff as implemented by ReconnectingSession, unless the library consumer intentionally wants to cancel connecting based on that error.
Only in the case of a permanent connection failure do we want to cancel the connection process and return an error to the consumer.
Therefore, we expose all connection errors to the library consumer via the Disconnect handler, allowing them, if they so choose, to .Close() an open session that is erroring (e.g., on authentication …

session: allow ReconnectingSession to retry temporary failures

---

session.go

Allow library consumers to customize the TLS configuration used by the agent on connection. We expose this as a callback, rather than a direct override of the TLS config, so that users can make tweaks without having to e.g. hardcode a region server name or the like.

session: allow custom TLS configuration

---

config/tls_termination.go
config/tls_termination_test.go

Resolves #86
We'll probably want to add a `WithAgentTermination` as well, but that
will be a little more involved, and may fit into the built-in connection
forwarding better.

Deprecate WithTermination in favor of clearer WithEdgeTermination and WithCustomEdgeTermination

---

session.go

Fixing this to match ngrok-rust.

session: rename WithChildClient to WithClientInfo

---

internal/muxado/buffer.go
internal/muxado/stream.go
online_test.go

Back in the day, Go didn't have very good cancellation semantics. I
mean, it still doesn't, but it's "better."
All of the old io interfaces lack a context argument to check
to see if their blocking call has been canceled. Therefore, if you
spawn off a "reader" task, how do you tell it to quit reading? You can
handle exiting the loop easy enough on your own, but what if the `Read`
method never returns? You still need a way to cancel _that_.
The solution? `Conn.SetDeadline` to "a long time ago!"
No, seriously:
```go
func (cr *connReader) abortPendingRead() {
cr.lock()
defer cr.unlock()
if !cr.inRead {
return
}
cr.aborted = true
cr.conn.rwc.SetReadDeadline(aLongTimeAgo)
for cr.inRead {
cr.cond.Wait()
}
cr.conn.rwc.SetReadDeadline(time.Time{})
}
```
To be fair, its usage as a cancellation …

fix (and test) websockets

---

internal/tunnel/proto/msg.go
session.go

Taking advantage of a new field that'll be used to surface warnings about old versions that will stop working in the future.

ngrok: surface deprecation warnings through the session

---

config/user_agent_filter.go
config/user_agent_filter_test.go

aligning the terminology for:
`WithAllowUserAgentFilter` and `WithDenyUserAgentFilter` ->   `WithAllowUserAgent` and `WithDenyUserAgent`
to be consistent with `WithAllowCIDR`/`WithDenyCIDR` / Use less text for

update user agent filter flags to be consistent

---

config/config_test.go
config/forwards_to_test.go
config/http_test.go
config/labeled_test.go
config/metadata_test.go
config/scheme_test.go
config/tcp_test.go
config/tls_test.go

This PR simplifies tests in the `config` package.

config: replace labelsPtr, stringPtr with ptr in tests

---

online_test.go
scripts/Makefile

This PR modifies online tests by adding code that closes the response body to prevent resource leaks. Additionally, we enable `bodyclose` linter to automatically catch those mistakes.
From the [documentation](https://pkg.go.dev/net/http):
> The caller must close the response body when finished with it
Also, see this [article](https://golang50shad.es/index.html#close_http_resp_body) for a deep dive into the problem.

online_test: close response body; enable bodyclose linter

---

config/cidr_restrictions_test.go
config/http_headers_test.go
config/oauth_test.go
config/oidc_test.go
config/user_agent_filter_test.go
errors_test.go
session_test.go

This PR simplifies test asserts.
Changes:
- replace `require.Len+require.Contains` with `require.ElementsMatch` or `require.Equal`;
- replace `require.Equal(t, err.Error(), ...)` with `require.EqualError(t, err, ...)`;
- replace `require.True(t, errors.As(...))` with `require.ErrorAs(...)`;
- replace `require.Len(t, slice, 0)` with `require.Empty(t, slice)`;
- reverse actual and expected values in some asserts.

test: refactor asserts

---

config/basic_auth_test.go
config/cidr_restrictions_test.go
config/circuit_breaker_test.go
config/common.go
config/compression_test.go
config/domain_test.go
config/forwards_to_test.go
config/http.go
config/http_headers.go
config/http_headers_test.go
config/http_test.go
config/labeled.go
config/labeled_test.go
config/metadata_test.go
config/mutual_tls_test.go
config/oauth_test.go
config/oidc_test.go
config/proxy_proto_test.go
config/scheme_test.go
config/tcp.go
config/tcp_test.go
config/tls.go
config/tls_termination_test.go
config/tls_test.go
config/tunnel_config.go
config/user_agent_filter_test.go
config/webhook_verification_test.go
config/websocket_tcp_conversion_test.go
session.go
tunnel_config.go

This also fixes a bug where the `forwards_to` field wasn't getting set because
we weren't using a pointer receiver to the `WithForwardsTo` builder hook.

ngrok: add option to auto-rewrite the host header on ListenAndForward

---

config/basic_auth.go
config/cidr_restrictions.go
config/circuit_breaker.go
config/compression.go
config/domain.go
config/forwards_to.go
config/http.go
config/http_headers.go
config/labeled.go
config/mutual_tls.go
config/oauth.go
config/oidc.go
config/tcp.go
config/tls.go
config/tls_termination.go
config/user_agent_filter.go
config/webhook_verification.go
config/websocket_tcp_conversion.go

~First pass at docs.~
~~There'll be another pass converting them all to permalinks, but this gets the~~
~~final destinations in place so that I can do a single perma pass after we get~~
~the OK on the permalinks themselves.~
All links should be correct as of this change. Since Product is going to handle redirects on the ngrok/ngrok-docs side, there won't be a permalinking pass after all.

Add missing doc links and update broken ones

---

config/user_agent_filter.go

This was a breaking change that snuck through.
Add some aliases that un-break it so that we're good semver citizens.

ngrok: add deprecated aliases for UserAgent filter options

---

forward.go
internal/tunnel/client/tunnel.go
tunnel.go

Most https backends will only expect http/2 if it's in the ALPN extension to
the TLS handshake. Therefore, if we send them http/2 without making them aware
of it, bad things will happen.

ngrok: negotiate http/2 with tls backends if the http2 AppProtocol is requested

---

.envrc
.github/workflows/buildandtest.yml
.gitignore
online_test.go

Some tests worked with unauthenticated sessions, which no longer work at all.
Make sure they're either authenticated or gone.
Also some miscellaneous testing improvements, such as dotenv support, better
logging, and better timeouts on the `exited` channel.

ngrok: fix tests after anonymous deprecation

---

.envrc
.github/workflows/buildandtest.yml
.gitignore
internal/tunnel/client/raw_session.go
internal/tunnel/client/raw_session_test.go
online_test.go
tunnel.go

Resolves #150
This is a little awkward.
First off, we need to preserve the fact that the latency channel gets closed.
Downstream code relies on this property.
The big problem is that the process sending things on the latency channel is
completely out-of-band with regard to the Close method. Ideally, the Heartbeat
type would also take a "cleanup" closure that would only be called after all of
its goroutines have exited, but that's a muxado change that I don't really want
to make right now.
Instead, we just have to make `Close` and `onHeartbeat` race-free.

internal: fix a panic due to a racy Close routine

---

internal/tunnel/client/raw_session.go
internal/tunnel/client/reconnecting.go
internal/tunnel/client/session.go
internal/tunnel/proto/msg.go
session.go

Adding support for multiple session legs.
This adds two configuration options:
- `WithAdditionalServers(addrs []string)`
- `WithMultiLeg(enable bool)`
If multi-leg is enabled, then the `ConnectAddresses` in the Auth response of the first session are used to determine what additional sessions should be set up. The `ReconnectingSession` will accumulate more sessions on connect, then return as normal. `ReconnectionSession` will handle fan-out of calls to the underlying `tunnel_client.Session` as before, except now there are multiple of them.
If the first connection is made using least-latency, it will lock in to that `ConnectAddress` so reconnects will go back to the same region. Heartbeat callbacks are done for each underlying session, including appropriate region and latency information.

multiple session legs support

---

log/log15/LICENSE.txt
log/logrus/LICENSE.txt
log/slog/LICENSE.txt
log/zap/LICENSE.txt

It seems like the license symlinks in the log adapter modules aren't being picked up by pkg.go.dev and preventing the docs from being displayed: https://pkg.go.dev/golang.ngrok.com/ngrok/log/slog
Seems to be a known issue:
https://github.com/golang/go/issues/40586

replace log adapter module license symlinks with full files

---

forward.go
forward_test.go

Before, the following would not work as you would expect:
```go
// # One terminal
// $ ncat --recv-only -l 9090
// ngrok-go code
fwd, err := sess.ListenAndForward(
ctx,
"127.0.0.1:9090",
config.TCPEndpoint(),
)
// fwd.URL() is 0.tcp.jp.ngrok.io:14517 for this example
// another terminal
// $ ncat --send-only 0.tcp.jp.ngrok.io 14517 < hello-world.txt
```
What we would expect from the above would be for the send side to send "hello world" and exit, and then the recv side to print "hello world" and also exit.
This is what happens if you do `ncat --send-only localhost 9090` instead of copying through the ngrok tcp tunnel.
Before this change, when copying through ngrok the recv side would not exit because the 'Close' of the connection did not get propagated through the 'join'.
I've also added …

Propagate half-closes correctly in forward

---

CHANGELOG.md
config/bindings.go
config/bindings_test.go
config/common.go
config/config_test.go
config/http.go
config/tcp.go
config/tls.go
internal/tunnel/proto/msg.go

Support WithBindings() mixin for all agent endpoint types

Add WithBindings Mixin

---

.github/workflows/buildandtest.yml
go.mod

Supersedes #182 
Adds a check to make sure that go mod tidy produces no diff for the go.mod or go.sum files.
Also updates some of our actions versions while we are here.

feat(ci): Add check for go mod tidy

---

CHANGELOG.md
config/policy.go
config/policy_test.go

This change adds a `WithTrafficPolicy` function for configuring traffic policy on a tunnel. This has the exact same behavior as `WithPolicyString` and solely exists to bring naming in line with the rest of the product. 
`WithPolicyString` now just calls `WithTrafficPolicy`. 
`WithPolicyString` doc string has been updated to include a deprecation warning.

alias `WithTrafficPolicy` to `WithPolicyString`

---

CHANGELOG.md

This captures the rest of the changes since the `v1.10.0` release

update changelog for v1.11.0 release

---

internal/tunnel/client/session.go

I was looking specifically for the `client.addr` and didn't see it being logged anywhere. We were previously logging this in the ngrok-operator project when we were handling dialing the upstream and joining connections on our own. Now that we are using an endpoint forwarder to clean up code in the ngrok-operator, we no longer see these logs messages when increasing log verbosity.
Inside `handleProxy` seemed like the most reasonable place to log this. It still feels like there might be a little bit of overlap with https://github.com/ngrok/ngrok-go/blob/15e612c3535344f175a06bc3d286cb6977ff2768/internal/tunnel/client/raw_session.go#L167. However, we don't have the `client.addr` there, so we can't add it there.
I'm hoping this will be generally useful, but if we don't think it will be, we can …

feat: Increase logging around proxy conn
